steps:
# Build the container image
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=gcr.io/darius-332003/tv2tg-worker"
  - "--file=./worker/Dockerfile"
  - .
images:
- "gcr.io/darius-332003/tv2tg-worker"
